name: Azure VM Static Site Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run deployment script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x ./deploy.sh
            ./deploy.sh
