name: Deploy Static Site to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.VM_IP }}" >> ~/.ssh/known_hosts

    - name: Upload and deploy static site
      run: |
        # Upload DevFolio directory to VM's home directory
        scp -o StrictHostKeyChecking=no -r DevFolio azureuser@${{ secrets.VM_IP }}:~/DevFolio

        # SSH into VM: clean old files, copy new ones, and restart NGINX
        ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_IP }} << 'EOF'
          sudo rm -rf /var/www/html/*
          sudo cp -r ~/DevFolio/* /var/www/html/
          sudo systemctl restart nginx
        EOF
